apiVersion: v1
kind: Pod
metadata:
  name: pod-secure2
  namespace: audit-zone
spec:
  containers:
    - name: nginx
      image: nginx
      securityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop: ["ALL"]
        seccompProfile:
          type: "RuntimeDefault"
      volumeMounts:
      - name: some-volume
        mountPath: /tmp
  volumes:
    - name: some-volume
      emptyDir:
        sizeLimit: 500Mi