apiVersion: v1
kind: Pod
metadata:
  name: pod-secure3
  namespace: audit-zone
spec:
  containers:
    - name: nginx
      image: nginx
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop: ["ALL"]        
        seccompProfile:
          type: "RuntimeDefault"
